---
title: "Growth and inhibition functions"
author: "Owen Petchey"
date: '2022-09-16'
output: html_document
---

# Growth and inhibition functions

The rate of change in population densities is given by the growth rate - death rate (Bush *et al.* 2018). Growth rate is the growth rate in absence of any inhibition multiplied by the amount of inhibition. 

Growth rate in the absence of inhibition was modeled with the Monod equation with multiplicative kinetics when two substrates determine growth rate:

$g_j(X, Y) = g_{max,j} (\frac{X}{K_{j,X} + X})(\frac{Y}{K_{j,Y} + Y})$

$g_{max,j}$ is the maximum specific growth rate of strain $j$. $X$ is the concentration of substrate 1, and $Y$ is the concentration of substrate 2. $K_{j,X}$ and $K_{j,Y}$ are the half-saturation constants of species $j$ on substrates $X$ and $Y$.

Inhibition of growth by a substrate was modelled with the Haldane equation:

$h_j(X) = \frac{1}{1+ (X / H_{j,X})}$

$H_{j,X}$ can be thought of as a half-inhibition constant: the concentration of $X$ at which the growth rate of species $j$ is reduced by 50%.

For further information details of the functions used to model system, please see the original publication by Bush *et al.* (2018)