---
title: "Summary1"
author: "Owen Petchey"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r}
library(tidyverse)
library(here)

library(microxanox)
if (packageVersion("microxanox") < package_version("0.3.0")) {
  stop("microxanox version needs to be at least 0.3.0!")
}
library(patchwork)
source(here("R/various_useful_functions.r"))
```


```{r}
stab_data_3s <- readRDS(here("experiments/3_strains/data/stab_data_1e6_x2x6_factorial.RDS")) %>%
  mutate(num_strains = 3) %>%
  select(1:6, 11:25)

stab_data_6s <- readRDS(here("experiments/6_strains/data/stab_data_1e6_x2x6_factorial.RDS")) %>%
  mutate(num_strains = 6) %>%
  select(1:6, 11:25)


stab_data_9s <- readRDS(here("experiments/9_strains/data/small_stab_data_1e6_x2x6_factorial.RDS")) 

stab_data <- stab_data_3s %>%
  bind_rows(stab_data_6s) %>%
  bind_rows(stab_data_9s)



```


```{r eval = plot_ss_results}
CB_vars <- unique(stab_data$CB_var_gmax_s)
SB_vars <- unique(stab_data$SB_var_gmax_s)

CB_stab_data <- stab_data %>%
  filter(SB_var_gmax_s == 0) %>%
  mutate(var_treat = "CB",
         var_gmax = CB_var_gmax_s)

SBPB_stab_data <- stab_data %>%
  filter(CB_var_gmax_s == 0) %>%
  mutate(var_treat = "SB-PB",
         var_gmax = SB_var_gmax_s)

for_join <- tibble(CB_var_gmax_s = sort(CB_vars),
                     SB_var_gmax_s = sort(SB_vars))
CBSBPB_stab_data <- stab_data %>%
  right_join(for_join) %>%
  mutate(var_treat = "CB-SB-PB",
         var_gmax = CB_var_gmax_s)

all_stab_results <- CB_stab_data %>%
  bind_rows(SBPB_stab_data) %>%
#  bind_rows(results3) %>%
 # bind_rows(results4) %>%
  bind_rows(CBSBPB_stab_data)

all_stab_results <- all_stab_results %>%
    mutate(var_treat = forcats::fct_relevel(var_treat, levels = c("CB", "SB-PB", "CB-SB-PB")))

#saveRDS(all_stab_results, here("experiments/experiment summary/all_stab.RDS"))


#all_stab_results <- readRDS(here("experiments/experiment summary/all_stab.RDS"))
```

### Log transformed

```{r eval = plot_ss_results}
all_stab_results %>%
  filter(Species == "O") %>%
  ggplot(aes(x = var_gmax, y = hyst_range_log, col=var_treat,
             shape = as_factor(num_strains))) +
  geom_point() +
  xlab("Amount of trait variation\n[see text for units]") +
  ylab("Extent of bistability region\n[log10 oxygen diffusivity]") +
  labs(col = "Variation in\nonly these\nfunctional groups")
##ggsave("manuscript/figures/extent_of_bistab1.pdf", height = 4)

all_stab_results %>%
  filter(Species == "O") %>%
  ggplot(aes(x = num_strains, y = hyst_range_log)) +
  facet_grid(var_gmax ~ var_treat, scales = "fixed") +
  geom_point() +
  xlab("Amount of trait variation\n[see text for units]") +
  ylab("Extent of bistability region\n[log10 oxygen diffusivity]") +
  labs(col = "Variation in\nonly these\nfunctional groups")
##ggsave("manuscript/figures/extent_of_bistab1.pdf", height = 4)


all_stab_results %>%
  #filter(var_treat == "CB") %>%
  filter(Species == "O",
         sim_length == 1e6) %>%
  ggplot(aes(x = var_gmax,
             ymin = hyst_min_log,
             ymax = hyst_max_log,
             fill=var_treat)) +
  geom_ribbon(alpha = 0.5) +
  facet_grid(num_strains ~ var_treat) +
  xlab("Amount of trait variation\n[see text for units]") +
  ylab("Oxygen diffusivity\n[log10 uM per hour]") +
  labs(fill = "Variation in\nonly these\nfunctional groups") +
  coord_flip() +
  theme(
    strip.background = element_blank(),
    strip.text.x = element_blank()
  )

##ggsave("manuscript/figures/extent_of_bistab2.pdf", height = 4)
stab_data %>%
  filter(Species == "O",
         sim_length == 1e6) %>%
  ggplot(aes(x = CB_var_gmax_s, y = SB_var_gmax_s, fill = hyst_range_log, col = hyst_range_log)) +
  geom_point(size = 3)


##ggsave("manuscript/figures/extent_of_bistab2.pdf", height = 4)

stab_data %>%
  filter(Species == "O",
         sim_length == 1e6) %>%
  ggplot(aes(x = CB_var_gmax_s, y = hyst_range_log, col = as.factor(SB_var_gmax_s))) +
  geom_line(size = 2)
```



# Zoom in on an effect

```{r}


ss_data_3s <- readRDS(here("experiments/3_strains/data/ss_data_1e6_x2x6_factorial.RDS")) %>%
  filter(abs(CB_var_gmax_s - 0.023268699) < 0.000001 &
           abs(SB_var_gmax_s - 0.0698061) < 0.000001)

p1  <- plot_ss_result1(ss_data_3s,
                result_index = 1,
                filename_prefix = NULL,
                save_image_file = FALSE)
p1



ss_data_6s <- readRDS(here("experiments/6_strains/data/ss_data_1e6_x2x6_factorial.RDS"))  %>%
  filter(abs(CB_var_gmax_s - 0.023268699) < 0.000001 &
           abs(SB_var_gmax_s - 0.0698061) < 0.000001)
p1  <- plot_ss_result1(ss_data_6s,
                result_index = 1,
                filename_prefix = NULL,
                save_image_file = FALSE)
p1




ss_data_9s <- readRDS(here("experiments/9_strains/data/ss_data_1e6_x2x6_factorial.RDS"))  %>%
  filter(abs(CB_var_gmax_s - 0.023268699) < 0.000001 &
           abs(SB_var_gmax_s - 0.0698061) < 0.000001)
p1  <- plot_ss_result1(ss_data_9s,
                result_index = 1,
                filename_prefix = NULL,
                save_image_file = FALSE)
p1



p_overlay1 <- plot_ss_result2(ss_data_3s$ss_res[[1]],
                             ss_data_6s$ss_res[[1]],
                             xlims = c(-7, -1))
p_overlay1


p_overlay1 <- plot_ss_result2(ss_data_3s$ss_res[[1]],
                             ss_data_9s$ss_res[[1]],
                             xlims = c(-7, -1))
p_overlay1



```

A O2 diff of around -5.2 we should be able to get bistability in the 3 strain system, and only anoxic in the 9 strain. At -1.55 we should be able to get bistability in the 3 strain system, but only oxic in the 9 strain.

```{r}

parameter <- new_runsim_parameter(
  dynamic_model = ss_data_3s$ss_by_a_N_result[[1]]$dynamic_model,
  event_definition = ss_data_3s$ss_by_a_N_result[[1]]$event_definition,
  event_interval = 100000,
  noise_sigma = ss_data_3s$ss_by_a_N_result[[1]]$noise_sigma,
  minimum_abundances = ss_data_3s$ss_by_a_N_result[[1]]$minimum_abundances,
  sim_duration = 1000000,
  sim_sample_interval = 100,
  strain_parameter = ss_data_3s$ss_by_a_N_result[[1]]$strain_parameter,
  log10a_series = c(NA, NA)
)
parameter$minimum_abundances["CB"] <- 10
parameter$minimum_abundances["SB"] <- 10
parameter$minimum_abundances["PB"] <- 10

parameter$strain_parameter$initial_state[grep("SB_", names(parameter$strain_parameter$initial_state))] <- parameter$strain_parameter$initial_state[grep("SB_", names(parameter$strain_parameter$initial_state))] / length(parameter$strain_parameter$initial_state[grep("SB_", names(parameter$strain_parameter$initial_state))])

parameter$strain_parameter$initial_state[grep("PB_", names(parameter$strain_parameter$initial_state))] <- parameter$strain_parameter$initial_state[grep("PB_", names(parameter$strain_parameter$initial_state))] / length(parameter$strain_parameter$initial_state[grep("PB_", names(parameter$strain_parameter$initial_state))])

parameter$log10a_series <- c(-5.2, -5.2)

## start with high CB abundance
parameter$strain_parameter$initial_state[grep("CB_", names(parameter$strain_parameter$initial_state))] <- 10^10/nrow(ss_data_3s$ss_by_a_N_result[[1]]$strain_parameter$CB)
sim_res_3s <- run_simulation(parameter)
plot_dynamics(sim_res_3s)

## start with low CB abundance
parameter$strain_parameter$initial_state[grep("CB_", names(parameter$strain_parameter$initial_state))] <- 10^0/nrow(ss_data_3s$ss_by_a_N_result[[1]]$strain_parameter$CB)
sim_res_3s <- run_simulation(parameter)
plot_dynamics(sim_res_3s)


```

```{r}

parameter <- new_runsim_parameter(
  dynamic_model = ss_data_9s$ss_by_a_N_result[[1]]$dynamic_model,
  event_definition = ss_data_9s$ss_by_a_N_result[[1]]$event_definition,
  event_interval = 100000,
  noise_sigma = ss_data_9s$ss_by_a_N_result[[1]]$noise_sigma,
  minimum_abundances = ss_data_9s$ss_by_a_N_result[[1]]$minimum_abundances,
  sim_duration = 1000000,
  sim_sample_interval = 100,
  strain_parameter = ss_data_9s$ss_by_a_N_result[[1]]$strain_parameter,
  log10a_series = c(NA, NA)
)

parameter$minimum_abundances["CB"] <- 10
parameter$minimum_abundances["SB"] <- 10
parameter$minimum_abundances["PB"] <- 10

parameter$strain_parameter$initial_state[grep("SB_", names(parameter$strain_parameter$initial_state))] <- parameter$strain_parameter$initial_state[grep("SB_", names(parameter$strain_parameter$initial_state))] / length(parameter$strain_parameter$initial_state[grep("SB_", names(parameter$strain_parameter$initial_state))])

parameter$strain_parameter$initial_state[grep("PB_", names(parameter$strain_parameter$initial_state))] <- parameter$strain_parameter$initial_state[grep("PB_", names(parameter$strain_parameter$initial_state))] / length(parameter$strain_parameter$initial_state[grep("PB_", names(parameter$strain_parameter$initial_state))])

parameter$log10a_series <- c(-5.2, -5.2)

## start with high CB abundance
parameter$strain_parameter$initial_state[grep("CB_", names(parameter$strain_parameter$initial_state))] <- 10^10/nrow(ss_data_9s$ss_by_a_N_result[[1]]$strain_parameter$CB)
sim_res_9s <- run_simulation(parameter)
plot_dynamics(sim_res_9s)

## start with low CB abundance
parameter$strain_parameter$initial_state[grep("CB_", names(parameter$strain_parameter$initial_state))] <- 10^0/nrow(ss_data_9s$ss_by_a_N_result[[1]]$strain_parameter$CB)
sim_res_9s <- run_simulation(parameter)
plot_dynamics(sim_res_9s)


```






At -1.55 we should be able to get bistability in the 3 strain system, but only oxic in the 9 strain.

```{r}

parameter <- new_runsim_parameter(
  dynamic_model = ss_data_3s$ss_by_a_N_result[[1]]$dynamic_model,
  event_definition = ss_data_3s$ss_by_a_N_result[[1]]$event_definition,
  event_interval = 100000,
  noise_sigma = ss_data_3s$ss_by_a_N_result[[1]]$noise_sigma,
  minimum_abundances = ss_data_3s$ss_by_a_N_result[[1]]$minimum_abundances,
  sim_duration = 1000000,
  sim_sample_interval = 100,
  strain_parameter = ss_data_3s$ss_by_a_N_result[[1]]$strain_parameter,
  log10a_series = c(NA, NA)
)
parameter$minimum_abundances["CB"] <- 10
parameter$minimum_abundances["SB"] <- 10
parameter$minimum_abundances["PB"] <- 10

parameter$strain_parameter$initial_state[grep("SB_", names(parameter$strain_parameter$initial_state))] <- parameter$strain_parameter$initial_state[grep("SB_", names(parameter$strain_parameter$initial_state))] / length(parameter$strain_parameter$initial_state[grep("SB_", names(parameter$strain_parameter$initial_state))])

parameter$strain_parameter$initial_state[grep("PB_", names(parameter$strain_parameter$initial_state))] <- parameter$strain_parameter$initial_state[grep("PB_", names(parameter$strain_parameter$initial_state))] / length(parameter$strain_parameter$initial_state[grep("PB_", names(parameter$strain_parameter$initial_state))])

parameter$log10a_series <- c(-1.6, -1.6)

## start with high CB abundance
parameter$strain_parameter$initial_state[grep("CB_", names(parameter$strain_parameter$initial_state))] <- 10^10/nrow(ss_data_3s$ss_by_a_N_result[[1]]$strain_parameter$CB)
sim_res_3s <- run_simulation(parameter)
plot_dynamics(sim_res_3s)

## start with low CB abundance
parameter$strain_parameter$initial_state[grep("CB_", names(parameter$strain_parameter$initial_state))] <- 10^0/nrow(ss_data_3s$ss_by_a_N_result[[1]]$strain_parameter$CB)
sim_res_3s <- run_simulation(parameter)
plot_dynamics(sim_res_3s)


```

```{r}

parameter <- new_runsim_parameter(
  dynamic_model = ss_data_9s$ss_by_a_N_result[[1]]$dynamic_model,
  event_definition = ss_data_9s$ss_by_a_N_result[[1]]$event_definition,
  event_interval = 100000,
  noise_sigma = ss_data_9s$ss_by_a_N_result[[1]]$noise_sigma,
  minimum_abundances = ss_data_9s$ss_by_a_N_result[[1]]$minimum_abundances,
  sim_duration = 1000000,
  sim_sample_interval = 100,
  strain_parameter = ss_data_9s$ss_by_a_N_result[[1]]$strain_parameter,
  log10a_series = c(NA, NA)
)

parameter$minimum_abundances["CB"] <- 10
parameter$minimum_abundances["SB"] <- 10
parameter$minimum_abundances["PB"] <- 10

parameter$strain_parameter$initial_state[grep("SB_", names(parameter$strain_parameter$initial_state))] <- parameter$strain_parameter$initial_state[grep("SB_", names(parameter$strain_parameter$initial_state))] / length(parameter$strain_parameter$initial_state[grep("SB_", names(parameter$strain_parameter$initial_state))])

parameter$strain_parameter$initial_state[grep("PB_", names(parameter$strain_parameter$initial_state))] <- parameter$strain_parameter$initial_state[grep("PB_", names(parameter$strain_parameter$initial_state))] / length(parameter$strain_parameter$initial_state[grep("PB_", names(parameter$strain_parameter$initial_state))])

parameter$log10a_series <- c(-1.6, -1.6)

## start with high CB abundance
parameter$strain_parameter$initial_state[grep("CB_", names(parameter$strain_parameter$initial_state))] <- 10^10/nrow(ss_data_9s$ss_by_a_N_result[[1]]$strain_parameter$CB)
sim_res_9s <- run_simulation(parameter)
plot_dynamics(sim_res_9s)

## start with low CB abundance
parameter$strain_parameter$initial_state[grep("CB_", names(parameter$strain_parameter$initial_state))] <- 10^0/nrow(ss_data_9s$ss_by_a_N_result[[1]]$strain_parameter$CB)
sim_res_9s <- run_simulation(parameter)
plot_dynamics(sim_res_9s)


```

